<a href="https://colab.research.google.com/github/chetan7116desai/TEAM_A_data606/blob/main/EDA/ipynb/Capstone_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
cd "/content/drive/Shareddrives/Team A 606 Capstone Project/Dataset/AllVAERSDataCSVS"

In [ ]:
ls "/content/drive/Shareddrives/Team A 606 Capstone Project/Dataset/AllVAERSDataCSVS"

In [ ]:
import pandas as pd
import glob
import seaborn as sns

Code to save all the vaccinations, symtoms, data file and combining them together into 3 different files:

Reference:https://pbpython.com/excel-file-combine.html

VAERSVAX DATA

In [ ]:

glob.glob("/content/drive/Shareddrives/Team A 606 Capstone Project/Dataset/AllVAERSDataCSVS/*VAERSVAX.csv")

In [ ]:
all_data_vax = pd.DataFrame()
for f in glob.glob("/content/drive/Shareddrives/Team A 606 Capstone Project/Dataset/AllVAERSDataCSVS/*VAERSVAX.csv"):
    VAX = pd.read_csv(f,encoding='latin1', engine='python')
    df_vax = all_data_vax.append(VAX,ignore_index=True)

In [ ]:
df_vax.head()

In [ ]:
df_vax.to_csv("/content/drive/Shareddrives/Team A 606 Capstone Project/Dataset/data_vax.csv")

VAERSSYMPTOMS

In [ ]:
df_vax.info()

In [ ]:
all_data_symptoms = pd.DataFrame()
for f in glob.glob("/content/drive/Shareddrives/Team A 606 Capstone Project/Dataset/AllVAERSDataCSVS/*VAERSSYMPTOMS.csv"):
    SYMP = pd.read_csv(f,encoding='latin1', engine='python')
    df_symp = all_data_symptoms.append(SYMP,ignore_index=True)

In [ ]:
df_symp.head()

In [ ]:
df_symp.to_csv("/content/drive/Shareddrives/Team A 606 Capstone Project/Dataset/data_sym.csv")

In [ ]:
df_symp = pd.read_csv("/content/drive/Shareddrives/Team A 606 Capstone Project/Dataset/data_sym.csv")

In [ ]:
df_symp.info()

VAERSDATA

In [ ]:
all_data_DATA = pd.DataFrame()
for f in glob.glob("/content/drive/Shareddrives/Team A 606 Capstone Project/Dataset/AllVAERSDataCSVS/*VAERSDATA.csv"):
    DATA = pd.read_csv(f,encoding='latin1', engine='python')
    df_data = all_data_DATA.append(DATA,ignore_index=True)

In [ ]:
df_data.head()

   VAERS_ID    RECVDATE STATE  ...  OFC_VISIT  ER_ED_VISIT  ALLERGIES
0     25002  07/02/1990    FR  ...        NaN          NaN        NaN
1     25010  07/02/1990    FR  ...        NaN          NaN        NaN
2     25011  07/02/1990    FR  ...        NaN          NaN        NaN
3     25064  07/02/1990    FR  ...        NaN          NaN        NaN
4     25055  07/09/1990    FR  ...        NaN          NaN        NaN

[5 rows x 35 columns]

In [ ]:
df_data.to_csv("/content/drive/Shareddrives/Team A 606 Capstone Project/Dataset/data_pat.csv")

In [ ]:
df_data.info()



* df_vax contains all the combined csv files of vaccinations from the year 1990 to 2022

* df_symp contains all the combined csv files of symptoms from the year 1990 to 2022

* df_data contains all the combined csv files of data from the year 1990 to 2022

In [ ]:
print(df_data["VAERS_ID"].nunique())
print(df_symp["VAERS_ID"].nunique())
print(df_vax["VAERS_ID"].nunique())

In [ ]:
print(df_data.shape)
print(df_symp.shape)
print(df_vax.shape)

(451105, 35)
(695132, 12)
(506017, 8)

In [ ]:
df_covid_data = df_vax[df_vax['VAX_TYPE'] == 'COVID19']
#df_covid_data.drop_duplicates( keep="first", inpla ce=True)
print(df_covid_data["VAERS_ID"].nunique())

340800

In [ ]:
covis_vaersid = df_covid_data.VAERS_ID.tolist()

In [ ]:
df_covid_data

        VAERS_ID VAX_TYPE  ... VAX_SITE                             VAX_NAME
149040    902854  COVID19  ...      NaN  COVID19 (COVID19 (PFIZER-BIONTECH))
149041    902855  COVID19  ...      NaN  COVID19 (COVID19 (PFIZER-BIONTECH))
149042    902856  COVID19  ...      NaN  COVID19 (COVID19 (PFIZER-BIONTECH))
149324    907571  COVID19  ...      NaN  COVID19 (COVID19 (PFIZER-BIONTECH))
149326    907573  COVID19  ...      NaN  COVID19 (COVID19 (PFIZER-BIONTECH))
...          ...      ...  ...      ...                                  ...
506011   2071532  COVID19  ...      NaN          COVID19 (COVID19 (MODERNA))
506013   2071536  COVID19  ...      NaN          COVID19 (COVID19 (MODERNA))
506014   2071537  COVID19  ...      NaN          COVID19 (COVID19 (MODERNA))
506015   2071539  COVID19  ...       LA          COVID19 (COVID19 (MODERNA))
506016   2071541  COVID19  ...      NaN          COVID19 (COVID19 (MODERNA))

[342013 rows x 8 columns]

In [ ]:
def sanitycheck(df):
    """
    Generates Unique count, Null Count and Null Percentage for each column in Dataframe
    
    Parameters
    ---------
    Input pandas dataframe
    
    Output: pandas dataframe
    """
    data = []
    for col in df.columns:
        data.append({'Column' : col,'Unique' : len(df[col].unique()),
                'Null Count' : df[col].isnull().sum(),
                'Null Percentage' : round(df[col].isnull().sum()/df.shape[0]*100,2) })
    return pd.DataFrame(data).sort_values(['Null Percentage'],ascending=False)

In [ ]:
sanitycheck(df_covid_data)

            Column  Unique  Null Count  Null Percentage
6         VAX_SITE       9      298408            87.25
5        VAX_ROUTE       8      182553            53.38
3          VAX_LOT   11740      121911            35.65
0         VAERS_ID  340800           0             0.00
1         VAX_TYPE       1           0             0.00
2         VAX_MANU       4           0             0.00
4  VAX_DOSE_SERIES       8           7             0.00
7         VAX_NAME       4           0             0.00

In [ ]:
df_covid_data.drop(['VAX_SITE','VAX_ROUTE','VAX_LOT'], axis = 1,inplace = True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [ ]:

df_covid_data.drop_duplicates( keep="first", inplace=True)
df_covid_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 341917 entries, 149040 to 506016
Data columns (total 5 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   VAERS_ID         341917 non-null  int64
 1   VAX_TYPE         341917 non-null  object
 2   VAX_MANU         341917 non-null  object
 3   VAX_DOSE_SERIES  341910 non-null  object
 4   VAX_NAME         341917 non-null  object
dtypes: int64(1), object(4)
memory usage: 15.7+ MB

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

In [ ]:
df_covid_data.groupby(['VAERS_ID']).size().reset_index().rename(columns={0:'count'}).sort_values("count", ascending=False)

        VAERS_ID  count
302888   1996461      4
297610   1986831      3
338740   2067238      3
272558   1934139      3
330761   2052167      3
...          ...    ...
113617   1485849      1
113616   1485823      1
113615   1485822      1
113614   1485821      1
340799   2071541      1

[340800 rows x 2 columns]

In [ ]:
df_covid_data[df_covid_data.VAERS_ID == 1996461]

        VAERS_ID VAX_TYPE  ... VAX_DOSE_SERIES                     VAX_NAME
466803   1996461  COVID19  ...               3  COVID19 (COVID19 (MODERNA))
466804   1996461  COVID19  ...               1  COVID19 (COVID19 (UNKNOWN))
466805   1996461  COVID19  ...             UNK  COVID19 (COVID19 (UNKNOWN))
466806   1996461  COVID19  ...               2  COVID19 (COVID19 (UNKNOWN))

[4 rows x 5 columns]

In [ ]:
df_covid = df_data.merge(df_covid_data, on="VAERS_ID",how='right')
display(df_covid)

        VAERS_ID  ...                             VAX_NAME
0         902854  ...  COVID19 (COVID19 (PFIZER-BIONTECH))
1         902855  ...  COVID19 (COVID19 (PFIZER-BIONTECH))
2         902856  ...  COVID19 (COVID19 (PFIZER-BIONTECH))
3         907571  ...  COVID19 (COVID19 (PFIZER-BIONTECH))
4         907573  ...  COVID19 (COVID19 (PFIZER-BIONTECH))
...          ...  ...                                  ...
341912   2071532  ...          COVID19 (COVID19 (MODERNA))
341913   2071536  ...          COVID19 (COVID19 (MODERNA))
341914   2071537  ...          COVID19 (COVID19 (MODERNA))
341915   2071539  ...          COVID19 (COVID19 (MODERNA))
341916   2071541  ...          COVID19 (COVID19 (MODERNA))

[341917 rows x 39 columns]

In [ ]:
print(df_covid["VAERS_ID"].nunique())

340800

In [ ]:
df_covid[df_covid.duplicated(['VAERS_ID'])]

        VAERS_ID  ...                             VAX_NAME
3061      987127  ...          COVID19 (COVID19 (MODERNA))
3235      992508  ...  COVID19 (COVID19 (PFIZER-BIONTECH))
7436     1016432  ...          COVID19 (COVID19 (UNKNOWN))
7884     1021496  ...          COVID19 (COVID19 (MODERNA))
13656    1053410  ...          COVID19 (COVID19 (MODERNA))
...          ...  ...                                  ...
341660   2070567  ...  COVID19 (COVID19 (PFIZER-BIONTECH))
341661   2070567  ...          COVID19 (COVID19 (UNKNOWN))
341666   2070571  ...          COVID19 (COVID19 (UNKNOWN))
341680   2070589  ...          COVID19 (COVID19 (UNKNOWN))
341681   2070589  ...          COVID19 (COVID19 (UNKNOWN))

[1117 rows x 39 columns]

In [ ]:
sanitycheck(df_covid)

             Column  Unique  Null Count  Null Percentage
23         V_FUNDBY       1      341917           100.00
5           CAGE_MO       2      341914           100.00
7          RPT_DATE       1      341917           100.00
12         ER_VISIT       1      341917           100.00
27        PRIOR_VAX     115      341799            99.97
31     BIRTH_DEFECT       2      341482            99.87
15           X_STAY       2      340887            99.70
34        ALLERGIES     643      340361            99.54
4           CAGE_YR      92      340212            99.50
10         DATEDIED     398      332579            97.27
14         HOSPDAYS      91      332098            97.13
9              DIED       2      329278            96.30
11         L_THREAT       2      327272            95.72
32        OFC_VISIT       2      319738            93.51
33      ER_ED_VISIT       2      318124            93.04
16          DISABLE       2      312893            91.51
25          CUR_ILL   21671      303915            88.89
13         HOSPITAL       2      269021            78.68
24       OTHER_MEDS   46440      262318            76.72
3           AGE_YRS     125      197821            57.86
26          HISTORY   86354      187524            54.84
21         LAB_DATA  129893      155697            45.54
20          NUMDAYS     614       63699            18.63
18         VAX_DATE     826       38139            11.15
19       ONSET_DATE     590       30266             8.85
28         SPLTTYPE  288917        1670             0.49
17           RECOVD       4          84             0.02
35         VAX_TYPE       1           0             0.00
36         VAX_MANU       4           0             0.00
37  VAX_DOSE_SERIES       8           7             0.00
0          VAERS_ID  340800           0             0.00
30      TODAYS_DATE     404           6             0.00
29        FORM_VERS       1           0             0.00
22        V_ADMINBY       8           0             0.00
1          RECVDATE     389           0             0.00
8      SYMPTOM_TEXT  340605           1             0.00
6               SEX       3           0             0.00
2             STATE       1           0             0.00
38         VAX_NAME       4           0             0.00

In [ ]:
df_covid.drop(['V_FUNDBY','RECVDATE','RPT_DATE','SYMPTOM_TEXT','CAGE_YR','CAGE_MO','V_ADMINBY','FORM_VERS','TODAYS_DATE','SPLTTYPE','VAX_DATE','ONSET_DATE','VAX_NAME','PRIOR_VAX','OFC_VISIT','ER_ED_VISIT'],axis=1,inplace=True)

In [ ]:
df_covid

        VAERS_ID STATE  AGE_YRS  ... VAX_TYPE         VAX_MANU VAX_DOSE_SERIES
0         902854    FR     49.0  ...  COVID19  PFIZER\BIONTECH             UNK
1         902855    FR      NaN  ...  COVID19  PFIZER\BIONTECH             UNK
2         902856    FR      NaN  ...  COVID19  PFIZER\BIONTECH             UNK
3         907571    FR      NaN  ...  COVID19  PFIZER\BIONTECH             UNK
4         907573    FR      NaN  ...  COVID19  PFIZER\BIONTECH             UNK
...          ...   ...      ...  ...      ...              ...             ...
341912   2071532    FR     43.0  ...  COVID19          MODERNA               2
341913   2071536    FR     44.0  ...  COVID19          MODERNA               3
341914   2071537    FR     30.0  ...  COVID19          MODERNA               1
341915   2071539    FR     51.0  ...  COVID19          MODERNA               2
341916   2071541    FR     68.0  ...  COVID19          MODERNA             UNK

[341917 rows x 23 columns]

In [ ]:
df_covid.to_csv('/content/drive/Shareddrives/Team A 606 Capstone Project/Dataset/covid_data.csv')

In [ ]:
df_covid = pd.read_csv('/content/drive/Shareddrives/Team A 606 Capstone Project/Dataset/covid_data.csv')

#combining all the symptoms into a single column

In [ ]:
df_symp

In [ ]:
df_symp.drop(['SYMPTOMVERSION1','SYMPTOMVERSION2','SYMPTOMVERSION3','SYMPTOMVERSION4','SYMPTOMVERSION5'],axis=1,inplace=True)

In [ ]:
sanitycheck(df_symp)

In [ ]:
df_covid_sym = df_symp[df_symp.VAERS_ID.isin(covis_vaersid)]

In [ ]:
df_covid_sym.VAERS_ID.nunique()

340800

In [ ]:
df_covid_sym[df_covid_sym.duplicated(['VAERS_ID'])]

In [ ]:
df_symp.duplicated(subset=['VAERS_ID']).sum ()

In [ ]:
df_symp.loc[df_symp.duplicated(subset=['VAERS_ID']), :]

        Unnamed: 0  ...                              SYMPTOM5
11              11  ...                                   NaN
17              17  ...                             Urticaria
26              26  ...                                   NaN
29              29  ...                               Syncope
31              31  ...                                   NaN
...            ...  ...                                   ...
695114      695114  ...                                   NaN
695118      695118  ...                                   NaN
695125      695125  ...  Vaccination site movement impairment
695126      695126  ...                                   NaN
695130      695130  ...                                   NaN

[244027 rows x 7 columns]

In [ ]:
cols = ['SYMPTOM1', 'SYMPTOM2', 'SYMPTOM3', 'SYMPTOM4','SYMPTOM5']
df_covid_sym["Symptoms"] = df_covid_sym[cols].apply(lambda x: ','.join(x.dropna()), axis=1)
#df_symp['Symptoms'] = df_symp['SYMPTOM1'] + "," +  df_symp['SYMPTOM2'] + "," +  df_symp['SYMPTOM3'] + "," +  df_symp['SYMPTOM4'] + "," +  df_symp['SYMPTOM5']
#https://stackoverflow.com/questions/45787782/combine-multiple-columns-in-pandas-excluding-nans

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
df_covid_sym

In [ ]:
df_covid_sym = df_covid_sym.groupby(['VAERS_ID','Symptoms']).size().reset_index().rename(columns={0:'count'})

In [ ]:
#df_symp.head(30)

df_covid_all_sym = df_covid_sym.groupby('VAERS_ID')['Symptoms'].apply(','.join).reset_index()

In [ ]:
df_covid_all_sym

In [ ]:
df_covid_all_sym.VAERS_ID.duplicated().sum()

In [ ]:
df_covid_all_sym.nunique()

In [ ]:
df_covid_all_sym[df_covid_all_sym.VAERS_ID ==902854]

In [ ]:
from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt

In [ ]:
df_covid_all_sym.info()

In [ ]:
df_covid_all_sym[df_covid_all_sym.VAERS_ID ==902854].Symptoms

In [ ]:
wordcloud2 = WordCloud(width=1600, height=800, 
            background_color ='white',min_font_size = 10).generate(' '.join(df_covid_all_sym.Symptoms))

In [ ]:
plt.figure(figsize=(15,15))
plt.imshow(wordcloud2)
plt.axis("off")
plt.show()
plt.savefig('/content/drive/Shareddrives/Team A 606 Capstone Project/Plot/sympworlcloud.jpeg')

In [ ]:
unique_ade = [val.strip() for sublist in df_covid_all_sym.Symptoms.dropna().str.split(",").tolist() for val in sublist]

In [ ]:
len(unique_ade)

In [ ]:
symptoms_summary = pd.DataFrame(unique_ade,columns=['symptoms']).value_counts(sort=True).reset_index().rename(columns={0:'count'})

In [ ]:
## Drop 15 covid symptoms
symptoms_summary[1:51]

In [ ]:
plt.figure(figsize=(10,10))
chart = sns.barplot(data=symptoms_summary[1:26], x="symptoms", y="count",palette='Set2')
chart.set_xticklabels(chart.get_xticklabels(), rotation=90)
plt.title('To 25 Covid Symptoms')
plt.xlabel('Symptoms')
plt.ylabel('No of cases')
plt.show()
plt.savefig('/content/drive/Shareddrives/Team A 606 Capstone Project/Plot/covidsymptoms.jpeg')

## MMR Vaccine

In [ ]:
df_mmr_vax= df_vax.query('VAX_TYPE == "MMRV" | VAX_TYPE == "MMR"')

In [ ]:
df_mmr_vax

In [ ]:
df_mmr_vax.VAERS_ID.nunique()

In [ ]:
sanitycheck(df_mmr_vax)

In [ ]:
df_mmr_vax.drop(['VAX_SITE','VAX_ROUTE','VAX_LOT','VAX_DOSE_SERIES'], axis = 1,inplace = True)

In [ ]:
df_mmr_vax.drop_duplicates( keep="first", inplace=True)
df_mmr_vax.info()

In [ ]:
df_mmr_vax.groupby(['VAERS_ID']).size().reset_index().rename(columns={0:'count'}).sort_values("count", ascending=False)

      VAERS_ID  count
7942    837705      2
8050    847206      2
8421    871003      2
8532    876166      2
6742    739407      2
...        ...    ...
3109    363875      1
3110    363876      1
3111    363877      1
3112    363879      1
9324   2064240      1

[9325 rows x 2 columns]

In [ ]:
df_mmr_vax[df_mmr_vax.VAERS_ID == 837705]

In [ ]:
df_mmr = df_data.merge(df_mmr_vax, on="VAERS_ID",how='right')
display(df_mmr)

In [ ]:
print(df_mmr["VAERS_ID"].nunique())

In [ ]:
df_mmr[df_mmr.duplicated(['VAERS_ID'])]

In [ ]:
sanitycheck(df_mmr)

In [ ]:
df_mmr.drop(['V_FUNDBY','RECVDATE','RPT_DATE','SYMPTOM_TEXT','CAGE_YR','CAGE_MO','V_ADMINBY','FORM_VERS','TODAYS_DATE','SPLTTYPE','VAX_DATE','ONSET_DATE','VAX_NAME','PRIOR_VAX','OFC_VISIT','ER_ED_VISIT'],axis=1,inplace=True)

In [ ]:
df_mmr

In [ ]:
df_mmr.to_csv('/content/drive/Shareddrives/Team A 606 Capstone Project/Dataset/mmr_data.csv')

HEPATITIS VACCINATION

In [ ]:
#reference: https://stackoverflow.com/questions/29461185/filtering-pandas-dataframe-using-or-statement
df_hepatitis_data = df_vax[(df_vax['VAX_TYPE'] =='HEP') | (df_vax['VAX_TYPE'] =='HEPA') | (df_vax['VAX_TYPE'] =='HEPAB') | (df_vax['VAX_TYPE'] =='HEPATYP')]

In [ ]:
print(df_hepatitis_data["VAERS_ID"].nunique())

In [ ]:
# df_PNC_data = df_vax[df_vax['VAX_TYPE'] == 'PNC13']
# #df_covid_data.drop_duplicates( keep="first", inpla ce=True)
# print(df_PNC_data["VAERS_ID"].nunique())

In [ ]:
df_hepatitis_data

        VAERS_ID VAX_TYPE  ... VAX_SITE                       VAX_NAME
2          25011      HEP  ...      NaN              HEP B (ENGERIX-B)
3          25055      HEP  ...      NaN              HEP B (ENGERIX-B)
4          25056      HEP  ...      NaN              HEP B (ENGERIX-B)
5          25057      HEP  ...      NaN              HEP B (ENGERIX-B)
6          25058      HEP  ...      NaN              HEP B (ENGERIX-B)
...          ...      ...  ...      ...                            ...
504055   2067410      HEP  ...      NaN          HEP B (NO BRAND NAME)
504061   2067412      HEP  ...      NaN          HEP B (NO BRAND NAME)
504334   2067680      HEP  ...      NaN          HEP B (RECOMBIVAX HB)
504360   2067782    HEPAB  ...      NaN  HEP A + HEP B (NO BRAND NAME)
504672   2069388      HEP  ...      NaN              HEP B (ENGERIX-B)

[17034 rows x 8 columns]

In [ ]:
hepatitis_vaersid = df_hepatitis_data.VAERS_ID.tolist()

In [ ]:
sanitycheck(df_hepatitis_data)

            Column  Unique  Null Count  Null Percentage
3          VAX_LOT    4244       10297            60.45
6         VAX_SITE      10        7335            43.06
5        VAX_ROUTE      14        3762            22.09
0         VAERS_ID   16238           0             0.00
1         VAX_TYPE       4           0             0.00
2         VAX_MANU       6           0             0.00
4  VAX_DOSE_SERIES       8           0             0.00
7         VAX_NAME      12           0             0.00

In [ ]:
df_hepatitis_data.drop(['VAX_SITE','VAX_ROUTE','VAX_LOT'], axis = 1,inplace = True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [ ]:
df_hepatitis_data.drop_duplicates( keep="first", inplace=True)
df_hepatitis_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16960 entries, 2 to 504672
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   VAERS_ID         16960 non-null  int64
 1   VAX_TYPE         16960 non-null  object
 2   VAX_MANU         16960 non-null  object
 3   VAX_DOSE_SERIES  16960 non-null  object
 4   VAX_NAME         16960 non-null  object
dtypes: int64(1), object(4)
memory usage: 795.0+ KB

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

In [ ]:
df_hepatitis_data.groupby(['VAERS_ID']).size().reset_index().rename(columns={0:'count'}).sort_values("count", ascending=False)

       VAERS_ID  count
14891    861217      5
14499    826233      5
14582    833492      4
14933    863313      4
14882    860236      4
...         ...    ...
5488     267614      1
5489     267615      1
5490     267693      1
5491     267695      1
16237   2069388      1

[16238 rows x 2 columns]

In [ ]:
df_hepatitis_data[df_hepatitis_data.VAERS_ID == 861217]

        VAERS_ID VAX_TYPE  ... VAX_DOSE_SERIES               VAX_NAME
137809    861217      HEP  ...               1      HEP B (ENGERIX-B)
137810    861217      HEP  ...               2      HEP B (ENGERIX-B)
137811    861217      HEP  ...               3      HEP B (ENGERIX-B)
137812    861217      HEP  ...             UNK      HEP B (ENGERIX-B)
137815    861217     HEPA  ...             UNK  HEP A (NO BRAND NAME)

[5 rows x 5 columns]

In [ ]:
df_hepatitis = df_data.merge(df_hepatitis_data, on="VAERS_ID",how='right')
display(df_hepatitis)

       VAERS_ID    RECVDATE  ... VAX_DOSE_SERIES                       VAX_NAME
0         25011  07/02/1990  ...             UNK              HEP B (ENGERIX-B)
1         25055  07/09/1990  ...             UNK              HEP B (ENGERIX-B)
2         25056  07/09/1990  ...             UNK              HEP B (ENGERIX-B)
3         25057  07/09/1990  ...             UNK              HEP B (ENGERIX-B)
4         25058  07/09/1990  ...             UNK              HEP B (ENGERIX-B)
...         ...         ...  ...             ...                            ...
16955   2067410  01/27/2022  ...               1          HEP B (NO BRAND NAME)
16956   2067412  01/27/2022  ...               1          HEP B (NO BRAND NAME)
16957   2067680  01/27/2022  ...             UNK          HEP B (RECOMBIVAX HB)
16958   2067782  01/27/2022  ...             UNK  HEP A + HEP B (NO BRAND NAME)
16959   2069388  01/27/2022  ...             UNK              HEP B (ENGERIX-B)

[16960 rows x 39 columns]

In [ ]:
print(df_hepatitis["VAERS_ID"].nunique())

16238

In [ ]:
df_hepatitis[df_hepatitis.duplicated(['VAERS_ID'])]

       VAERS_ID    RECVDATE  ... VAX_DOSE_SERIES               VAX_NAME
263       72906  04/04/1995  ...               2         HEP A (HAVRIX)
514       89261  08/23/1996  ...             UNK         HEP A (HAVRIX)
581       92038  11/18/1996  ...             UNK         HEP A (HAVRIX)
612       92812  12/12/1996  ...             UNK         HEP A (HAVRIX)
616       92815  12/12/1996  ...             UNK         HEP A (HAVRIX)
...         ...         ...  ...             ...                    ...
16928   2016478  01/08/2022  ...               1  HEP B (NO BRAND NAME)
16932   2022739  01/11/2022  ...               2      HEP B (ENGERIX-B)
16933   2022739  01/11/2022  ...               1      HEP B (ENGERIX-B)
16938   2029201  01/12/2022  ...               2  HEP B (NO BRAND NAME)
16939   2029201  01/12/2022  ...               3  HEP B (NO BRAND NAME)

[722 rows x 39 columns]

In [ ]:
sanitycheck(df_hepatitis)

             Column  Unique  Null Count  Null Percentage
34        ALLERGIES       7       16954            99.96
31     BIRTH_DEFECT       2       16952            99.95
33      ER_ED_VISIT       2       16830            99.23
32        OFC_VISIT       2       16737            98.69
10         DATEDIED     222       16715            98.56
9              DIED       2       16444            96.96
15           X_STAY       2       16297            96.09
11         L_THREAT       2       16266            95.91
12         ER_VISIT       2       16086            94.85
5           CAGE_MO      12       15431            90.98
27        PRIOR_VAX     264       15001            88.45
16          DISABLE       2       14921            87.98
14         HOSPDAYS      55       14731            86.86
30      TODAYS_DATE    1029       13397            78.99
4           CAGE_YR      83       11162            65.81
24       OTHER_MEDS    1947       10598            62.49
26          HISTORY    3989       10441            61.56
13         HOSPITAL       2       10011            59.03
25          CUR_ILL    1752        8432            49.72
20          NUMDAYS     842        5860            34.55
19       ONSET_DATE    5943        5309            31.30
21         LAB_DATA    7479        5116            30.17
3           AGE_YRS     240        5052            29.79
18         VAX_DATE    6203        3866            22.79
7          RPT_DATE    4737        3859            22.75
23         V_FUNDBY       5        3563            21.01
17           RECOVD       4        1090             6.43
28         SPLTTYPE   14908          64             0.38
36         VAX_MANU       6           0             0.00
35         VAX_TYPE       4           0             0.00
37  VAX_DOSE_SERIES       8           0             0.00
0          VAERS_ID   16238           0             0.00
29        FORM_VERS       2           0             0.00
22        V_ADMINBY       5           0             0.00
1          RECVDATE    5284           0             0.00
8      SYMPTOM_TEXT   16197           0             0.00
6               SEX       3           0             0.00
2             STATE       1           0             0.00
38         VAX_NAME      12           0             0.00

In [ ]:
df_hepatitis.drop(['V_FUNDBY','RECVDATE','RPT_DATE','SYMPTOM_TEXT','CAGE_YR','CAGE_MO','V_ADMINBY','FORM_VERS','TODAYS_DATE','SPLTTYPE','VAX_DATE','ONSET_DATE','VAX_NAME','PRIOR_VAX','OFC_VISIT','ER_ED_VISIT'],axis=1,inplace=True)

In [ ]:
df_hepatitis

       VAERS_ID STATE  ...                     VAX_MANU VAX_DOSE_SERIES
0         25011    FR  ...           SMITHKLINE BEECHAM             UNK
1         25055    FR  ...           SMITHKLINE BEECHAM             UNK
2         25056    FR  ...           SMITHKLINE BEECHAM             UNK
3         25057    FR  ...           SMITHKLINE BEECHAM             UNK
4         25058    FR  ...           SMITHKLINE BEECHAM             UNK
...         ...   ...  ...                          ...             ...
16955   2067410    FR  ...         UNKNOWN MANUFACTURER               1
16956   2067412    FR  ...         UNKNOWN MANUFACTURER               1
16957   2067680    FR  ...             MERCK & CO. INC.             UNK
16958   2067782    FR  ...         UNKNOWN MANUFACTURER             UNK
16959   2069388    FR  ...  GLAXOSMITHKLINE BIOLOGICALS             UNK

[16960 rows x 23 columns]

In [ ]:
df_hepatitis.to_csv('/content/drive/Shareddrives/Team A 606 Capstone Project/Dataset/hepatitis_data.csv')

In [ ]:
df_hepatitis = pd.read_csv('/content/drive/Shareddrives/Team A 606 Capstone Project/Dataset/hepatitis_data.csv')

#combining all the symptoms into a single column

In [ ]:
df_hepatitis_sym = df_symp[df_symp.VAERS_ID.isin(hepatitis_vaersid)]

In [ ]:
df_hepatitis_sym.VAERS_ID.nunique()

16238

In [ ]:
df_hepatitis_sym[df_hepatitis_sym.duplicated(['VAERS_ID'])]

        Unnamed: 0  VAERS_ID  ...             SYMPTOM4   SYMPTOM5
17              17     25540  ...  Rash maculo-papular  Urticaria
26              26     25653  ...                  NaN        NaN
29              29     25711  ...                Shock    Syncope
31              31     25712  ...                  NaN        NaN
34              34     25807  ...                  NaN        NaN
...            ...       ...  ...                  ...        ...
681582      681582   2053418  ...                  NaN        NaN
682281      682281   2055036  ...                  NaN        NaN
691041      691041   2066448  ...          Pharyngitis    Pyrexia
692311      692311   2067410  ...                  NaN        NaN
692693      692693   2067680  ...                  NaN        NaN

[11853 rows x 7 columns]

In [ ]:
df_symp.duplicated(subset=['VAERS_ID']).sum ()

244027

In [ ]:
df_symp.loc[df_symp.duplicated(subset=['VAERS_ID']), :]

        Unnamed: 0  ...                              SYMPTOM5
11              11  ...                                   NaN
17              17  ...                             Urticaria
26              26  ...                                   NaN
29              29  ...                               Syncope
31              31  ...                                   NaN
...            ...  ...                                   ...
695114      695114  ...                                   NaN
695118      695118  ...                                   NaN
695125      695125  ...  Vaccination site movement impairment
695126      695126  ...                                   NaN
695130      695130  ...                                   NaN

[244027 rows x 7 columns]

In [ ]:
cols = ['SYMPTOM1', 'SYMPTOM2', 'SYMPTOM3', 'SYMPTOM4','SYMPTOM5']
df_hepatitis_sym["Symptoms"] = df_hepatitis_sym[cols].apply(lambda x: ','.join(x.dropna()), axis=1)
#df_symp['Symptoms'] = df_symp['SYMPTOM1'] + "," +  df_symp['SYMPTOM2'] + "," +  df_symp['SYMPTOM3'] + "," +  df_symp['SYMPTOM4'] + "," +  df_symp['SYMPTOM5']
#https://stackoverflow.com/questions/45787782/combine-multiple-columns-in-pandas-excluding-nans

In [ ]:
df_hepatitis_sym

In [ ]:
df_hepatitis_sym = df_hepatitis_sym.groupby(['VAERS_ID','Symptoms']).size().reset_index().rename(columns={0:'count'})

In [ ]:
#df_symp.head(30)

df_hepatitis_all_sym = df_hepatitis_sym.groupby('VAERS_ID')['Symptoms'].apply(','.join).reset_index()

In [ ]:
df_hepatitis_all_sym

In [ ]:
df_hepatitis_all_sym.VAERS_ID.duplicated().sum()

In [ ]:
df_hepatitis_all_sym.nunique()

In [ ]:
df_hepatitis_all_sym[df_hepatitis_all_sym.VAERS_ID ==2067410]

In [ ]:
df_hepatitis_all_sym.info()

In [ ]:
df_hepatitis_all_sym[df_hepatitis_all_sym.VAERS_ID ==2067410].Symptoms

In [ ]:
wordcloud3 = WordCloud(width=1600, height=800, 
            background_color ='white',min_font_size = 10).generate(' '.join(df_hepatitis_all_sym.Symptoms))

In [ ]:
plt.figure(figsize=(15,15))
plt.imshow(wordcloud3)
plt.axis("off")
plt.show()
plt.savefig('/content/drive/Shareddrives/Team A 606 Capstone Project/Plot/hepatitissymwordcloud.jpeg')

In [ ]:
hepatitis_unique_ade = [val.strip() for sublist in df_hepatitis_all_sym.Symptoms.dropna().str.split(",").tolist() for val in sublist]

In [ ]:
hepatitis_symptoms_summary = pd.DataFrame(hepatitis_unique_ade,columns=['symptoms']).value_counts(sort=True).reset_index().rename(columns={0:'count'})

In [ ]:
## Drop 15 covid symptoms
hepatitis_symptoms_summary[1:51]

In [ ]:

plt.figure(figsize=(10,10))
chart = sns.barplot(data=hepatitis_symptoms_summary[0:25], x="symptoms", y="count")
chart.set_xticklabels(chart.get_xticklabels(), rotation=90)
plt.title('To 25 Hepatitis Symptoms')
plt.xlabel('Symptoms')
plt.ylabel('No of cases')
plt.show()
plt.savefig('/content/drive/Shareddrives/Team A 606 Capstone Project/Plot/hepatitissymptoms.jpeg')

In [ ]:
df_hepatitis.head()